apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: app-operator
    app.kubernetes.io/managed-by: kustomize
  name: manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manager-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: app-operator-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: app-operator-controller-rolebinding
  namespace: app-operator-system
subjects:
- kind: ServiceAccount
  name: app-operator-controller-manager
  namespace: app-operator-system
roleRef:
  kind: ClusterRole
  name: app-operator-controller-role
  apiGroup: rbac.authorization.k8s.io
