---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - tools.vorozhko.net
  resources:
  - appoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tools.vorozhko.net
  resources:
  - appoperators/finalizers
  verbs:
  - update
- apiGroups:
  - tools.vorozhko.net
  resources:
  - appoperators/status
  verbs:
  - get
  - patch
  - update
